# Generated by Django 4.0.6 on 2022-09-02 22:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('agent_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='agent_id')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания агента')),
                ('surname', models.CharField(max_length=35, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=35, verbose_name='Отчество')),
                ('login', models.CharField(max_length=35, verbose_name='Логин')),
                ('password', models.CharField(max_length=35, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=100)),
                ('mobile_number', models.IntegerField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
                'ordering': ['surname', 'name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('client_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='client_id')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото клиента')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания клиента')),
                ('surname', models.CharField(max_length=35, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=35, verbose_name='Отчество')),
                ('entity', models.CharField(choices=[('Физ. лицо', 'Физическое лицо'), ('Юр. лицо', 'Юридическое лицо')], default='Физ. лицо', max_length=35, verbose_name='Признак страхования')),
                ('mobile_number', models.IntegerField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['date_create', 'surname', 'name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('insurance_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='insurance_id')),
                ('max_payment', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Страховая сумма(руб)')),
                ('cost', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Стоимость(руб)')),
                ('date_conclusion_contract', models.DateTimeField(auto_now_add=True, verbose_name='Дата заключения контракта')),
                ('period_start_date', models.DateField(verbose_name='Дата начала')),
                ('period_end_date', models.DateField(verbose_name='Дата окончания')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance95.agent', verbose_name='Агент')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance95.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Страховка',
                'verbose_name_plural': 'Страховки',
                'ordering': ['insurance_id'],
            },
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('region_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='region_id')),
                ('region_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['region_id', 'region_name'],
            },
        ),
        migrations.CreateModel(
            name='type_insurance',
            fields=[
                ('type_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='type_id')),
                ('type_name', models.CharField(db_index=True, max_length=100, verbose_name='Тип страховки')),
            ],
            options={
                'verbose_name': 'Тип страховки',
                'verbose_name_plural': 'Типы страховки',
                'ordering': ['type_id'],
            },
        ),
        migrations.CreateModel(
            name='type_service',
            fields=[
                ('type_service_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='type_service_id')),
                ('type_name', models.CharField(max_length=100, verbose_name='Тип дополнительной услуги')),
            ],
            options={
                'verbose_name': 'Тип доп. услуги',
                'verbose_name_plural': 'Тип доп. услуг',
                'ordering': ['type_service_id'],
            },
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('payment_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='payment_id')),
                ('plat_date', models.DateField()),
                ('plat', models.DecimalField(decimal_places=3, max_digits=18)),
                ('debt', models.DecimalField(decimal_places=3, max_digits=18)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance95.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='passport_date',
            fields=[
                ('passport_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='passport_id')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('surname', models.CharField(max_length=35, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=35, verbose_name='Отчество')),
                ('series', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Серия')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('data_issue', models.DateField(verbose_name='Дата выдачи')),
                ('division_code', models.CharField(max_length=10, verbose_name='Код подразделения')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Выдан')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('place_birth', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance95.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Паспортные данные',
                'verbose_name_plural': 'Паспортные данные',
                'ordering': ['surname', 'name', 'patronymic', 'date_birth'],
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance95.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance95.type_insurance', verbose_name='Тип страховки'),
        ),
        migrations.AddField(
            model_name='clients',
            name='passport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='insurance95.passport_date', verbose_name='Паспортные данные'),
        ),
        migrations.CreateModel(
            name='additional_service',
            fields=[
                ('additional_service_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='additional_service_id')),
                ('cost', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Стоимость')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance95.insurance', verbose_name='Основная страховка')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance95.type_service', verbose_name='Тип доп. услуги')),
            ],
            options={
                'verbose_name': 'Дополнительные услуга',
                'verbose_name_plural': 'Дополнительные услуги',
                'ordering': ['additional_service_id'],
            },
        ),
    ]
